# Generated by Django 5.0.3 on 2024-03-21 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_userdata_options_userdata_groups_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdata',
            options={},
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='user_permissions',
        ),
    ]
