services:
  - type: web
    name: django-backend
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: gunicorn OneOnOne.OneOnOne.wsgi:application
    envVarsFromFile: .env.render
