# Generated by Django 5.0.3 on 2024-03-12 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_contactrequest_unique_sender_receiver_pair'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contactrequest',
            name='unique_sender_receiver_pair',
        ),
    ]
