# Generated by Django 5.0.3 on 2024-03-13 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_contactrequest_unique_sender_receiver_pair'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contactrequest',
            name='unique_sender_receiver_pair',
        ),
    ]
