# Generated by Django 5.0.3 on 2024-04-08 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='status',
            field=models.TextField(choices=[('created', 'In Progress'), ('submitted', 'Submitted'), ('finalized', 'Finalized')], default='submitted'),
        ),
    ]
