# Generated by Django 5.0.3 on 2024-03-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0005_timeslotvote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='preference',
            field=models.IntegerField(choices=[(1, 'Low Preference'), (2, 'Medium Preference'), (3, 'High Preference')]),
        ),
        migrations.AlterField(
            model_name='timeslotvote',
            name='preference',
            field=models.IntegerField(choices=[(0, 'Not Available'), (1, 'Low Preference'), (2, 'Medium Preference'), (3, 'High Preference')]),
        ),
    ]
