# Generated by Django 5.0.3 on 2024-03-14 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0006_alter_timeslot_preference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslotvote',
            name='calendar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='calendars.calendar'),
        ),
    ]
