# Generated by Django 5.0.3 on 2024-03-14 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0008_alter_timeslotvote_calendar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslotvote',
            name='calendar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendars.calendar'),
        ),
    ]
