# Generated by Django 5.0.3 on 2024-04-07 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0009_alter_timeslotvote_calendar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='date_time_finalization',
        ),
        migrations.AddField(
            model_name='calendar',
            name='finalized_timeslot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finalizing_calendars', to='calendars.timeslot'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='status',
            field=models.TextField(choices=[('created', 'In Progress'), ('submitted', 'Submitted'), ('finalized', 'Finalized')], default='created'),
        ),
    ]
